name: zeno
description: "A calorie tracking app for finding your balance."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  # Firebase Packages
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Charting Library
  fl_chart: ^0.68.0

  # For beautiful typography from Google Fonts
  google_fonts: ^6.2.1

  # For date formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Add this line
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Path to your new icon
  
flutter_native_splash:
  color: "#F7F9F9"  # Your app's light background color
  image: assets/icon.png # Path to your new icon
  android_12:
    color: "#F7F9F9"
    image: assets/icon.png