name: zeno
description: "A calorie tracking app for finding your balance."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For State Management (simple and powerful)
  provider: ^6.1.2

  # For Local Database (fast and easy to use)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For beautiful typography from Google Fonts
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  # For making API calls to a food database later
  http: ^1.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For code generation with Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true