import 'package:hive/hive.dart';

part 'user_goal.g.dart'; // This file will be generated by the build_runner

@HiveType(typeId: 0)
class UserGoal extends HiveObject {
  @HiveField(0)
  double lbsToLose;

  @HiveField(1)
  int days;

  // Calculated properties are not stored in the database, but are very useful
  int get totalCalorieDeficit => (lbsToLose * 3500).round();
  int get dailyCalorieDeficitTarget => (totalCalorieDeficit / days).round();

  UserGoal({
    required this.lbsToLose,
    required this.days,
  });
}